name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  say_hello:
    name: Say hello on continuum
    runs-on: continuum
    defaults:
      run:
        shell: cmd
        working-directory: C:\Users\goodxdev    
    steps:
    - uses: actions/checkout@v2
    - run: copy C:\actions2\_work\hello-github-actions\hello-github-actions\README.md C:\Users\goodxdev
