name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  say_hello:
    name: Say hello on continuum
    runs-on: continuum
    defaults:
      run:
        shell: cmd
        working-directory: C:\Users\goodxdev    
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "Hello ${{ github.event.inputs.name }}!" > C:\Users\goodxdev\actions.log
        echo "- in ${{ github.event.inputs.home }}!" >> C:\Users\goodxdev\actions.log
