name: A workflow for my Hello World file
# manual
on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name'
        required: true  
  pull_request:
    types: [ opened, reopened ]
  pull_request_review:
    types: [ submitted ]
    
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      # - name: action-a
      #   uses: actions/checkout@v1
      # # - uses: ./action-a
      # #   with:
      # #     MY_NAME: "Mona"
          
      - name: echo-context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_BRANCH: ${{ github.event.inputs.branch_name || github.head_ref }}
          GITHUB_MAIN: ${{ github.ref }}      
        run: echo BRANCH "$GITHUB_BRANCH" && echo MAIN "$GITHUB_MAIN" && echo CONTEXT "$GITHUB_CONTEXT"
