name: A workflow for my Hello World file
on: [ workflow_dispatch, pull_request ] 

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      # - name: action-a
      #   uses: actions/checkout@v1
      # # - uses: ./action-a
      # #   with:
      # #     MY_NAME: "Mona"
          
      - name: echo-context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
