---

name: PR handler
on:
  pull_request:
    types: [ opened, closed, reopened ]
  pull_request_review:
      types: [ submitted ]


jobs:
  remove-all-labels:
    runs-on: ubuntu-latest
    steps:
      - name: remove all labels
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            Assigned
            ChangesRequested
            CodeReview
            TestForMerge
            ToBeTested

  mark-as-merged:
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: add MERGED label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ToBeTested

  mark-as-cr:
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - name: add CR label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: CodeReview

  mark-as-pr-approved:
    if: ${{ github.event_name == 'pull_request_review' && github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - name: add TFM label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: TestForMerge

  mark-as-pr-changes:
    if: ${{ github.event_name == 'pull_request_review' && github.event.review.state == 'changes_requested' }}
    runs-on: ubuntu-latest
    steps:
      - name: add ASSIGNED label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ChangesRequested
